name: ci

on:
  pull_request: {}
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

jobs:
  release: 
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Validate
        uses: joelanford/opm-validate@v0.1.0
        with:
          catalog: ./configs

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: quay.io/joelanford/example-catalog
          labels: |
            org.opencontainers.image.title=ExampleCatalog
            org.opencontainers.image.description=Example Catalog
            org.opencontainers.image.vendor=Example, Inc.
          tags: |
            type=ref,event=branch,enable=${{ ! endsWith(github.ref, github.event.repository.default_branch) }}
            type=ref,event=pr
            type=raw,value=latest,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}
          
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build
        uses: docker/bake-action@v1
        with:
          files: |
            ./docker-bake.hcl
            ${{ steps.meta.outputs.bake-file }}
          targets: build
          push: ${{ github.event_name != 'pull_request' }}
